### ISSUE TITLE
RUN install bundler error (FIXED)

### ISSUE THREAD

**Issue by rminana** [bunnylushington/api-doc-pipeline#1]
in the Dockerfile, the  comand RUN install bundler gives an error when is trying to install bundler.
I tried to replace the comand with gem install bundler, it RUN perfectly the build, but when it comes to run the image, it fails.

Any solution for this?

Thanks!

**Comment by rminana** [comment]
Finally I resolved this error by modifying the Dockerfile given. This config worked for me.

```
FROM ruby:2.6

RUN apt-get update && \
  apt-get install -y nodejs npm

RUN apt-get install -y libjson-xs-perl libyaml-perl

RUN apt-get install -y vim less

RUN mkdir /work
WORKDIR /work

# -- slate setup

RUN git clone https://github.com/slatedocs/slate.git
WORKDIR /work/slate
RUN gem install bundler
RUN bundler -v
RUN bundle install


# -- openapi2slate setup
WORKDIR /work
RUN npm -g i widdershins


# -- custom stuff
COPY ./yaml2json /work/yaml2json
COPY ./build     /work/build

CMD "/work/build"
```

I hope it helps to the future users.

**Comment by bunnylushington** [comment]
Hey thanks!  I'm not sure if that was code rot or what but I appreciate the heads up and the fix.
